Homepage was accessed at 2024-02-01 12:45:03.768207 hours!
Homepage was accessed at 2024-02-01 12:45:13.229653 hours!
Homepage was accessed at 2024-02-01 12:56:30.535802 hours!
Homepage was accessed at 2024-02-01 12:56:38.487533 hours!
Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\Alice\anaconda3\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alice\anaconda3\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\2024\pythonWork\blockchain\eadmin\views.py", line 15, in login
    email = form.cleaned_data['email']
            ^^^^^^^^^^^^^^^^^
AttributeError: 'LoginParticpantForm' object has no attribute 'cleaned_data'
Not Found: /favicon.ico
Internal Server Error: /login/
Traceback (most recent call last):
  File "E:\python_anaconda\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\python_anaconda\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Binu\Django Project\blockchain\eadmin\views.py", line 15, in login
    email = form.cleaned_data['email']
            ^^^^^^^^^^^^^^^^^
AttributeError: 'LoginParticpantForm' object has no attribute 'cleaned_data'
login page was accessed at 2024-02-01 11:01:27.916718 hours!kavitha@gmail.com,kavitha
Internal Server Error: /login/
Traceback (most recent call last):
  File "E:\python_anaconda\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\python_anaconda\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Binu\Django Project\blockchain\eadmin\views.py", line 21, in login
    logger.warning('login page was accessed at '+str(datetime.datetime.now())+' hours!'+email+','+userid)
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
TypeError: can only concatenate str (not "int") to str
login page was accessed at 2024-02-01 11:08:06.758130 hours!kavitha@gmail.com,5
Internal Server Error: /login/
Traceback (most recent call last):
  File "E:\python_anaconda\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\python_anaconda\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Binu\Django Project\blockchain\eadmin\views.py", line 22, in login
    logger.warning('login page was accessed at '+str(datetime.datetime.now())+' hours!'+email+','+str(userid))
                                                                                                      ^^^^^^
NameError: name 'unedserid' is not defi
5
5
5
5
5
Internal Server Error: /bid_details/
Traceback (most recent call last):
  File "E:\python_anaconda\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\python_anaconda\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Binu\Django Project\blockchain\eadmin\views.py", line 45, in bid_details
    return render(request,"bid_details.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python_anaconda\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python_anaconda\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python_anaconda\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: bid_details.html
5
5
5
Internal Server Error: /bid_details/
Traceback (most recent call last):
  File "E:\python_anaconda\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\python_anaconda\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Binu\Django Project\blockchain\eadmin\views.py", line 45, in bid_details
    return render(request,"bid_details.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python_anaconda\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python_anaconda\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python_anaconda\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: bid_details.html
4
5
5
Not Found: /favicon.ico
5
Not Found: /favicon.ico
5
5
5
5
5
5
Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\python_anaconda\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\python_anaconda\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Binu\Django Project\blockchain\eadmin\views.py", line 44, in dashboard
    logger.warning(tenders.title)
                ^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'title'
5
['House Finance', 'Mouse', 'Job Tender']
Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\python_anaconda\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\python_anaconda\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Binu\Django Project\blockchain\eadmin\views.py", line 46, in dashboard
    logger.warning(tenders.title)
                ^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'title'
5
Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\python_anaconda\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\python_anaconda\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Binu\Django Project\blockchain\eadmin\views.py", line 44, in dashboard
    if tender_list:
       ^^^^^^^^^^^
NameError: name 'tender_list' is not defined
5
Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\python_anaconda\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\python_anaconda\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Binu\Django Project\blockchain\eadmin\views.py", line 44, in dashboard
    if tender_list:
       ^^^^^^^^^^^
NameError: name 'tender_list' is not defined
5
Tenders: <QuerySet [<tender: tender object (1)>, <tender: tender object (2)>, <tender: tender object (3)>]>
5
Tenders: <QuerySet [<tender: tender object (1)>, <tender: tender object (2)>, <tender: tender object (3)>]>
5
Tenders: <QuerySet [<tender: tender object (4)>, <tender: tender object (6)>]>
5
Tenders: <QuerySet [<tender: tender object (4)>, <tender: tender object (6)>]>
5
Tenders: <QuerySet [<tender: tender object (4)>, <tender: tender object (6)>]>
Internal Server Error: /viewBidDetails/4/
Traceback (most recent call last):
  File "E:\python_anaconda\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\python_anaconda\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: getBidDetails() got an unexpected keyword argument 'tender_id'
Internal Server Error: /viewBidDetails/4/
Traceback (most recent call last):
  File "E:\python_anaconda\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\python_anaconda\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Binu\Django Project\blockchain\eadmin\views.py", line 56, in getBidDetails
    tender=tender.objects.get(pk=tender_id)
           ^^^^^^
UnboundLocalError: cannot access local variable 'tender' where it is not associated with a value
